env_name: MountainCarContinuous-v0
seed_id: 0
eval_config:
  end_value: 999
  init_value: 999
  num_eval_envs: 50
  transition_begin: 0
  transition_steps: 1
inner_config:
  ddpg:
    agent_kwargs:
      activation: tanh
    batch_size: 100
    buffer_size: 2000
    env: MountainCarContinuous-v0
    eval_freq: 10000
    exploration_noise:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
    fill_buffer: 1000
    gamma:
      - 1.0
      - 0.99
      - 0.95
      - 0.9
      - 0.8
    gradient_steps: 1
    learning_rate:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
    max_grad_norm: 10
    num_envs: 1
    tau:
      - 0.99
      - 0.95
      - 0.9
      - 0.7
      - 0.8
    total_timesteps: 10000
  ppo:
    agent_kwargs:
      activation: tanh
    clip_eps:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
    ent_coef:
      - 0.0
      - 0.01
      - 0.05
      - 0.1
      - 0.5
    env: MountainCarContinuous-v0
    eval_freq: 10000
    gae_lambda:
      - 1.0
      - 0.95
      - 0.9
      - 0.8
      - 0.5
    gamma:
      - 1.0
      - 0.99
      - 0.95
      - 0.9
      - 0.8
    learning_rate:
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
    max_grad_norm: 10
    num_envs: 5
    num_epochs: 4
    num_minibatches: 4
    num_steps: 100
    total_timesteps: 10000
    vf_coef:
      - 0.0
      - 0.5
      - 1.0
      - 1.5
      - 2.0
  sac:
    agent_kwargs:
      activation: tanh
    batch_size: 256
    buffer_size: 2000
    env: MountainCarContinuous-v0
    eval_freq: 10000
    fill_buffer: 1000
    gamma:
      - 1.0
      - 0.99
      - 0.95
      - 0.9
      - 0.8
    gradient_steps: 2
    learning_rate:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
    num_envs: 5
    target_entropy_ratio: 0
    tau:
      - 0.99
      - 0.95
      - 0.9
      - 0.7
      - 0.8
    total_timesteps: 10000
  td3:
    actor_kwargs:
      activation: tanh
    batch_size: 100
    buffer_size: 10000
    critic_kwargs:
      activation: tanh
    env: MountainCarContinuous-v0
    eval_freq: 10000
    exploration_noise:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
    fill_buffer: 1000
    gamma:
      - 1.0
      - 0.99
      - 0.95
      - 0.9
      - 0.8
    learning_rate:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
    max_grad_norm: 10
    policy_delay: 2
    target_noise:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
    target_noise_clip:
      - 0.1
      - 0.4
      - 0.7
      - 1.0
      - 1.3
    tau:
      - 0.99
      - 0.95
      - 0.9
      - 0.7
      - 0.8
    total_timesteps: 10000
inner_loop_algorithm:
  - ppo
  - sac
  - ddpg
  - td3
meta_config:
  mean_eval_freq: 1
  num_generations: 300
  num_rollouts: 1
  num_rollouts_mean: 64
strategy_name: SNES
strategy_params:
  popsize: 128
  sigma_init: 0.05
  temperature: 0
synth_env_kwargs:
  max_steps_in_episode: 1
  network_kwargs:
    features:
      - 32
    latent_dist: normal
