env_name: CartPole-v1
seed_id: 0
eval_config:
  end_value: 500
  init_value: 500
  num_eval_envs: 50
  transition_begin: 0
  transition_steps: 1
inner_config:
  dqn:
    agent: DuelingQNetwork
    agent_kwargs:
      activation: tanh
    batch_size: 100
    buffer_size: 2000
    ddqn:
      - 1
      - 0
    env: CartPole-v1
    eps_end:
      - 0.01
      - 0.05
      - 0.1
      - 0.2
    eps_start: 1
    eval_freq: 10000
    exploration_fraction: 0.5
    fill_buffer: 1000
    gamma:
      - 1.0
      - 0.99
      - 0.95
      - 0.9
      - 0.8
    gradient_steps: 1
    learning_rate:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
    max_grad_norm: 10
    num_envs: 10
    target_update_freq: 50
    total_timesteps: 10000
  ppo:
    agent_kwargs:
      activation: tanh
    clip_eps:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
    ent_coef:
      - 0.0
      - 0.01
      - 0.05
      - 0.1
      - 0.5
    env: CartPole-v1
    eval_freq: 10000
    gae_lambda:
      - 1.0
      - 0.95
      - 0.9
      - 0.8
      - 0.5
    gamma:
      - 1.0
      - 0.99
      - 0.95
      - 0.9
      - 0.8
    learning_rate:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
    max_grad_norm: 10
    num_envs: 5
    num_epochs: 10
    num_minibatches: 10
    num_steps: 100
    total_timesteps: 10000
    vf_coef:
      - 0.0
      - 0.5
      - 1.0
      - 1.5
      - 2.0
  sac:
    agent_kwargs:
      activation: tanh
    batch_size: 256
    buffer_size: 2000
    env: CartPole-v1
    eval_freq: 10000
    fill_buffer: 1000
    gamma:
      - 1.0
      - 0.99
      - 0.95
      - 0.9
      - 0.8
    gradient_steps: 2
    learning_rate:
      - 0.01
      - 0.005
      - 0.001
      - 0.0005
      - 0.0001
    num_envs: 5
    target_entropy_ratio:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
    tau:
      - 0.99
      - 0.95
      - 0.9
      - 0.7
      - 0.8
    total_timesteps: 10000
inner_loop_algorithm:
  - ppo
  - sac
  - dqn
meta_config:
  mean_eval_freq: 1
  num_generations: 300
  num_rollouts: 1
  num_rollouts_mean: 64
strategy_name: SNES
strategy_params:
  popsize: 128
  sigma_init: 0.05
  temperature: 0
synth_env_kwargs:
  max_steps_in_episode: 1
  network_kwargs:
    features:
      - 32
    latent_dist: normal
